{{- if and (not .Values.backendScheduler.enabled) }}
{{ $dict := dict "ctx" . "component" "compactor" "memberlist" true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tempo.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" $dict | nindent 4 }}
  {{- with .Values.compactor.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  minReadySeconds: {{ .Values.compactor.minReadySeconds }}
{{- if not .Values.compactor.autoscaling.enabled }}
  replicas: {{ .Values.compactor.replicas }}
{{- end }}
  revisionHistoryLimit: {{ .Values.tempo.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" $dict | nindent 6 }}
{{- with .Values.compactor.strategy }}
  strategy:
{{- toYaml . | nindent 4 }}
{{- end }}
  template:
    {{- include "tempo.podTemplate" (dict "ctx" $ "component" .Values.compactor "target" "compactor") | nindent 4 }}
{{- end }}
