apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.name" . }}-runtime
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  runtime-config.yaml: |
    {{- if .Values.newConfig }}
    {{- tpl (toYaml .Values.runtimeConfig) . | nindent 4 }}
    {{- else }}
    {{- tpl (toYaml .Values.loki.runtimeConfig) . | nindent 4 }}
    {{- end }}
