---
loki:
  commonConfig:
    replication_factor: 1
  useTestSchema: true
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    type: s3
    s3:
      endpoint: rustfs:9000
      accessKeyId: rustfsadmin
      secretAccessKey: rustfsadmin
      s3ForcePathStyle: true
      insecure: true
deploymentMode: SimpleScalable

read:
  replicas: 1
write:
  replicas: 1
backend:
  replicas: 1

sidecar:
  rules:
    enabled: true

extraObjects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: rustfs
    spec:
      selector:
        app: rustfs
      ports:
        - name: http
          port: 9000
          targetPort: 9000
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: rustfs
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: rustfs
      template:
        metadata:
          labels:
            app: rustfs
        spec:
          containers:
            - name: rustfs
              image: docker.io/rustfs/rustfs:1.0.0
              ports:
                - containerPort: 9000
                  name: http
              env:
                - name: RUSTFS_ACCESS_KEY
                  value: "rustfsadmin"
                - name: RUSTFS_SECRET_KEY
                  value: "rustfsadmin"
              volumeMounts:
                - name: data
                  mountPath: /data
              readinessProbe:
                httpGet:
                  path: /health
                  port: http
                periodSeconds: 10
              startupProbe:
                exec:
                  command:
                    - mkdir
                    - -p
                    - /data/chunks/
                    - /data/ruler/
                    - /data/admin/
                initialDelaySeconds: 1
                periodSeconds: 1
                failureThreshold: 10
          volumes:
            - name: data
              emptyDir: {}
