{{- if .Values.liveStore.enabled }}
{{- $dict := dict "ctx" . "component" "live-store" "memberlist" true -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "tempo.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" $dict | nindent 4 }}
    {{- with .Values.liveStore.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.liveStore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.liveStore.replicas }}
  revisionHistoryLimit: {{ .Values.tempo.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" $dict | nindent 6 }}
  serviceName: live-store
  podManagementPolicy: Parallel
  updateStrategy:
    {{- toYaml .Values.liveStore.statefulStrategy | nindent 4 }}
  template:
    {{- include "tempo.podTemplate" (dict "ctx" $ "component" .Values.liveStore "target" "live-store") | nindent 4 }}
{{- end }}
